### ISSUE TITLE
Session not available inside constructor

### ISSUE THREAD

**Issue by sudhanshu2340** [tzsk/payu#12]
Hi, You are using session data for storage in paymentcontroller constructor but as this post suggest:
https://github.com/laravel/framework/issues/15048

see comment:
Oh, yeh, you totally can rely on the IOC, BUT you must not ever do anything with the request state. That includes sessions and auth. You can inject those classes for later though.

So either you move the storage initialization in individual function or roll back the cache. spent almost 5 hours on this to figure out.

Thanks

**Comment by fasilkk** [comment]
the same problem, is there any solution to fix this real quick?

**Comment by tzsk** [comment]
Okay... I have been working on the fix for the same. I will fix it and have a release ready by a couple of days.

If you guys have any fix. Please feel free to post a PR.

Thank you.

**Comment by tzsk** [comment]
Hi, @sudhanshu2340 & @fasilkk 

Please see the new Release 1.2.4. This issue has been fixed and updated.

Thank you for reporting the issue.
