### ISSUE TITLE
getting There is no Redirect URL specified error.

### ISSUE THREAD

**Issue by sachin99** [tzsk/payu#13]
I have installed this plugin as per instructions. i am getting following error.

![image](https://user-images.githubusercontent.com/6890464/29465852-55cb567c-8458-11e7-8c11-6b747964bfd2.png)

**Comment by tzsk** [comment]
Which version of the Package are you using? And what version of Laravel are you using it with?

**Comment by tzsk** [comment]
I have just now checked this Package v1.2.4 with Laravel 5.2, 5.3 and 5.4. And it is working fine.

I think you are using v1.2.3 which have a bug with 5.3 and above. Please run below command to update the package and let me know if you still face the issue:

```bash
composer update tzsk/payu
```

**Comment by sachin99** [comment]
Thanks for your help. i updated the package and its working now.
