### ISSUE TITLE
Get payUmoney details using transation ID

### ISSUE THREAD

**Issue by mit255** [tzsk/payu#151]
I have try 
Payment::verify("1612950218156")->full();
error :+  Call to undefined method stdClass::full()

I try to :  Payment::verify("1612950218156");
 
Client error: `POST https://www.payumoney.com/sandbox/payment/op/getPaymentResponse?merchantKey=sRkksn&merchantTransactionIds=1612950218156` resulted in a `401  ▶
    <html><head><title>PayUMoney - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;backgr (truncated...)

Please give me solution how to capture payment Using translation id.

**Comment by tzsk** [comment]
Please state your PHP Version, Laravel Version and Payu Package version.

I think you are referring to old docs.
