### ISSUE TITLE
Issue with config file

### ISSUE THREAD

**Issue by pm3724** [tzsk/payu#154]
Hi,

I am getting this error - Argument 1 passed to Tzsk\Payu\Payu::via() must be of the type string, null given, called in /var/www/astroprofit/vendor/tzsk/payu/src/Payu.php on line 55

I have tried to debug and cleared the cache - but when i use via while initiate, it redirects me as already specified in docs.

But i am not able to figure out what am i missing in config file.

I have make sure to publish all settings.

PHP Version: 7.4.3
Laravel Version: 8.11.2

Thanks

**Comment by tzsk** [comment]
I guess you are using wrong version of the Docs. And you're using the v5 of the package.

Please follow the readme for the updated docs. payu.tzskr.com

**Comment by pm3724** [comment]
I am using and referring to the right version - "tzsk/payu": "^5.1"
trying to integrate the PayU money

config ile - payu.php

'default' => env('PAYU_DEFAULT_GATEWAY', 'money'),

    'gateways' => [
        'money' => new PayuMoney([
            'mode' => env('PAYU_MONEY_MODE', Gateway::TEST_MODE),
            'key' => env('PAYU_MONEY_KEY', '****'),
            'salt' => env('PAYU_MONEY_SALT', '****'),
            'auth' => env('PAYU_MONEY_AUTH', '****'),
        ]),

**Comment by tzsk** [comment]
The method `via()` needs a string argument. Either `money` or `biz`
