### ISSUE TITLE
payumoney service provider 

### ISSUE THREAD

**Issue by nikhilpansare** [tzsk/payu#16]
Pay Money service_provider = 'payu_paisa' is unable to send to secure server .

Showing error
SORRY!
We were unable to process your payment

Error Reason
You seem to be using an incorrect key or salt value. 

But working on test environment

**Comment by tzsk** [comment]
@nikhilpansare It is not particularly tailored towards PayuMoney. This package is for PayuBiz. 

But you can add PayuMoney credentials and need to directly put 

`<input type="hidden" name="service_provider" value="payu_paisa">` 

in your `vendor/tzsk/payu/src/Views/payment_form.blade.php` after the `foreach` loop.

I would also suggest checking your `salt` and `key` just to be sure. The above mentioned way is just a hack. You cannot use the Payment Verification functionality if you use this package for PayuMoney.

Do let me know if you are able to integrate by the above mentioned way.

I might release a new version with support for `PayuMoney` for both making payment and verification.

**Comment by tzsk** [comment]
Please see Release `Version 2.0`.

PayuMoney Support Added
