### ISSUE TITLE
Test payment always goes to failed

### ISSUE THREAD

**Issue by Mohd-Hasan** [tzsk/payu#17]
I am using tzsk/payu package with laravel 5.4. after setting all things when i submitted payment details on payumoney test payment gateway, it always returns a Failed Transaction. I am not understanding what things are going wrong . please help

**Comment by tzsk** [comment]
@Mohd-Hasan This package is not for `PayuMoney` it is for `PayuBiz`. But yes it can be modified to use PayuMoney. But for that you have to make a few changes for yourself.

See Issue #16 for the details of how to make the changes for `PayuMoney`.

**Comment by Mohd-Hasan** [comment]
for payumoney test mode i added  <input type="hidden" name="service_provider" value=""> in payment_form.blade.php after foreach but transaction still failing.

**Comment by tzsk** [comment]
@Mohd-Hasan It is: `<input type="hidden" name="service_provider" value="payu_paisa">` you didn't put any value there.

**Comment by Mohd-Hasan** [comment]
I have tested with both but not working `value="payu_paisa"` and `value=""`

**Comment by Mohd-Hasan** [comment]
@tzsk thanks. problem has solved. actually the real problem was expiry date of test card.
