### ISSUE TITLE
Cancel Url

### ISSUE THREAD

**Issue by narendraraghuwanshi** [tzsk/payu#191]
How To i Pass Cancel URL 
Its Show me 404 page not found when i cancel in production mode

**Comment by tzsk** [comment]
Which version and which gateway are you using?

**Comment by narendraraghuwanshi** [comment]
I am using laravel 8 or gateway payumoney

> Which version and which gateway are you using?

**Comment by tzsk** [comment]
@narendraraghuwanshi The Failed URL is your cancel URL. Not sure what you mean.
