### ISSUE TITLE
Phone can not be null when payment was cancelled

### ISSUE THREAD

**Issue by Arpitasingh10** [tzsk/payu#20]
When i cancel payment from live mode it returns the  the following error.

(2/2) QueryExceptionSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'phone' cannot be null

**Comment by tzsk** [comment]
@Arpitasingh10 Phone is a mandatory field. Please let me know, did you send your phone number with the `$data` array?

**Comment by Arpitasingh10** [comment]
yes i am giving phone no..but still that error shown

**Comment by tzsk** [comment]
@Arpitasingh10 For now. You  can set the `phone` field nullable in the database. That should fix it. But the original fix will come in the next version.

Please let me know if you run into any other issue.

**Comment by tzsk** [comment]
@Arpitasingh10 Well, I have tested in many ways. It is perfectly working for me. I can't reproduce your issue. But I'll still make it optional in next release.

I am closing this issue for now. If this issue resurfaces again, I'll reopen.
