### ISSUE TITLE
Optional parameter not receive after payment

### ISSUE THREAD

**Issue by Mohd-Hasan** [tzsk/payu#21]
I have integrated this package with my project but one thing is creating trouble. I am passing an reg_id as optional parameter so that it receive me from gateway after transaction perform successfully or failed but i am not getting receive it.

```
$data = [
    'txnid' => strtoupper($tr_id), # Transaction ID.
    'amount' => $request->amt_inr, # Amount to be charged.
    'productinfo' => "Membership Fees",
    'firstname' => $request->name, # Payee Name.
    'email' => $request->email, # Payee Email Address.
    'phone' => $request->mobile, # Payee Phone Number.
   'reg_id'=>$reg_id #Member registration id
];
```

**Comment by tzsk** [comment]
That is not how `Payu Gateway` works (As Per Payu Official Documentation). You cannot just pass any field you like for your case it is `reg_id`. That is an invalid field and will be ignored. You have to use only the fields allowed. You can use the `udf1-udf5` for these type of use. That is why they exist in Payu.

**Comment by Mohd-Hasan** [comment]
O.k. Thank u brother.

**Comment by Mohd-Hasan** [comment]
One more thing when transaction completed `Payment::capture()` automatically insert values to table. i created a new field reg_id in `payu_payments` table and want to insert `udf1` value in it with other data. what should i do ?

**Comment by tzsk** [comment]
You shouldn't be asking this,

```php
$payment = Payment::capture();
$payment->reg_id = $payment->get('udf1');
$payment->save();
```
You can also use Model Events on `PayuPayment` model.

**Comment by Mohd-Hasan** [comment]
Sorry for this and thanks again
