### ISSUE TITLE
 database issue on localhost

### ISSUE THREAD

**Issue by Arpitasingh10** [tzsk/payu#22]
#1273 - Unknown collation: 'utf8mb4_unicode_ci'   when i open phpmyadmin this error is shown ..how can i solve it...???

**Comment by tzsk** [comment]
@Arpitasingh10 Were you able to successfully migrate the database by running `php artisan migrate`?

What PHP & MySQL version are you using?

What Laravel Version are you using?

**Comment by Arpitasingh10** [comment]
i am using vertrigo server .
PHP 5.2.6
Mysql 5.0.51b

this problem is not come in xampp server and also i am not using laravel

**Comment by tzsk** [comment]
@Arpitasingh10 Those versions are not compatible with Laravel 5 and above. 
You have to have,

Laravel 5.0 & 5.1
PHP >= 5.5.9
MySQL >= 5.6
-or-
MariaDB >= 10

AND

Laravel 5.5
PHP >= 7
MySQL >= 5.7

Please read the official Laravel Documentation to find out the exact requirements.
