### ISSUE TITLE
PAYU_MONEY_MODE=test is not working after the new payu website

### ISSUE THREAD

**Issue by rafienleo** [tzsk/payu#231]
Hi, how are you?
Recently after the PayU website was revamped, the test mode is no longer working.
Also, the `Auth` key value is no longer available from the Merchant Dashboard.

From the documentation
'Auth'
This is only required for PayuMoney gateway. You can get it from your merchant dashboard as well

**Comment by rafienleo** [comment]
Hey I found out from the new PayU documentation the test URL is changed
https://devguide.payu.in/merchant-integration/payu-hosted-checkout/payu-hosted-checkout-integration/

Test | https://test.payu.in/_payment
Production | https://secure.payu.in/_payment

**Comment by tzsk** [comment]
You're talking about payu money or payu biz?

**Comment by rafienleo** [comment]
money

**Comment by rafienleo** [comment]
> You're talking about payu money or payu biz?
money

**Comment by tzsk** [comment]
@rafienleo you are mistaken. Payu.IN is actually Payu BIZ. Payumoney.IN is Payu Money.

The link you pasted is Payu Biz. Here is the link for Payu Money. https://developer.payumoney.com/redirect/
