### ISSUE TITLE
Not able to install with laravel 9

### ISSUE THREAD

**Issue by SushilMore1988** [tzsk/payu#251]
Problem 1
    - Root composer.json requires tzsk/payu ^5.2 -> satisfiable by tzsk/payu[5.2.0].
    - tzsk/payu 5.2.0 requires illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

Changed php to ^7.0|^8.0 but still gives same error.

**Comment by tzsk** [comment]
It requires Laravel 7 or 8. Your project maybe using something that conflicts with illuminate / support 7 or 8

**Comment by tzsk** [comment]
@SushilMore1988 Update the package to `v6.0.0`. This works with Laravel 9
