### ISSUE TITLE
Currencies Integration for payu

### ISSUE THREAD

**Issue by aminammari** [tzsk/payu#30]
How to integrate currencies 
##Payu Integration

hello sir thanks for your previews answer please i wanna integrate multi-currencies  
or how to return a price from my website with selected currency

regards sir thanks for your greatest job

* Version used (e.g. PHP 5.6, HHVM 3):
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:
* ...
* ...

**Comment by tzsk** [comment]
You have to set currencies in the Payu Dashboard I guess or do the conversion within your app.
