### ISSUE TITLE
How do I refund the transactions?

### ISSUE THREAD

**Issue by mayur-novus** [tzsk/payu#31]
## This is a great library for making payments, but how about initiating a refund of the payment? How can I achieve this using this library? I did not find any documentation about it anywhere and also no code for refund in the library.

Can you add the refund APIs as well to this library?

This is an enhancement to the library.

## Context

I would like to refund the transactions to the users in case they cancel or return the items they purchased from my store. This would help me find an alternative to this library and I can do all PayU Money related tasks using this awesome library.

Refund is a critical part for any business. I am sure this will help other developers to take on this library as it would be a all in one wrapper for the payment gateway.

**Comment by tzsk** [comment]
I'll have to look into it if payu and payumoney has refund API.

**Comment by tzsk** [comment]
Payu doesn't have any api for refund. At least I can't find it.
