### ISSUE TITLE
Getting Payment not found error

### ISSUE THREAD

**Issue by parthvora-tecocraft** [tzsk/payu#311]
![image](https://user-images.githubusercontent.com/71762330/181252465-79e66fde-802d-47c2-b29e-c7b760695815.png)

I am using this payment method for payU but getting error 
'Payment'  not found

**Comment by tzsk** [comment]
@parthvora-tecocraft 

Why are you combining `v4` and `v5`?

`Payment::make($attributes, function () {})` syntax is not supported in `v5`.

Please also provide PHP Version & Laravel Payu Package Version.

**Comment by parthvora-tecocraft** [comment]
PHP version 8.0 
Laravel PayU package version 6

**Comment by parthvora-tecocraft** [comment]
I have followed this doc to create payment function
https://tzsk.github.io/payu/#/usage

**Comment by tzsk** [comment]
![Screenshot_2022-07-29-19-48-28-30_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/13273787/181785238-b5ce37ed-cb0b-4c47-9c70-d83398869c61.jpg)
