### ISSUE TITLE
Sandbox Integration 2022

### ISSUE THREAD

**Issue by arifkhn46** [tzsk/payu#313]
Recently I have encountered an issue with Sandbox integration, on making payments I was getting error "Sorry, Some Problem Occurred.". 

Following is the configuration that I am using in my project:

1. Gateway: Payu money
2. PAYU_MONEY_MODE: test
3. Url: https://sandboxsecure.payu.in/_payment

So I contacted the payu support team and they have told me to make following changes:

1. Please remove the below param from all your requests. service_provider
2. update the URL to https://test.payu.in/_payment

Now I have concern that what if one wants to change/update/remove one/more parameters, how that can be achieved. I guess here we need to make things little more flexible so that one can tweak think as per his/her needs.

**Comment by tzsk** [comment]
So essentially you're using PayuBiz not payu money. A lot of people confuse between them.

If you look at the PayuBiz config you'll see that what you are explaining is essentially that.

So use that gateway and it should be fine.

**Comment by arifkhn46** [comment]
In my project's .env file I haven't set PAYU_DEFAULT_GATEWAY and default configuration is as following: 

`return [
    'default' => env('PAYU_DEFAULT_GATEWAY', 'money'),
];`

So I am not using payu biz. By the way I forgot to mention that I am using version 5.2 of tzsk/payu.

**Comment by arifkhn46** [comment]
My apologies, I misunderstood it.
