### ISSUE TITLE
Cannot Post / Home/User

### ISSUE THREAD

**Issue by OMCHEVLI8484** [tzsk/payu#328]
data() {
    return {
      showProducts: true,
      id: "",
      disable: true,
      list: [],
      state: [],
      city: [],
      country: [],
      amount_pay: "300",
      products: [],
      email: "Om@gmail.com",
      mobile_no: "",
      first_name: "om",
      last_name: "",
      address: "",
      pincode: "",
      coupon_code: "",
      country_id: "101",
      state_id: "",
      city_id: "",
      productInfo: "Salesforce",
      paynowbtn: "",
      loading: "",
      // =================================Payment Data================================
      txnid: this.makeid(),
      payuUrl: "https://test.payu.in/_payment",
      mkey: "rjQUPktU",
      saltKey: "e5iIg1jwi8",
      surl: window.location.origin + "/home/User/Success",
      //surl: "http://localhost:8080/Success",
      furl: window.location.origin + "/home/User/Fail",
      //this.post("https://test.payu.in/_payment","post")

      // =========================For testing===============================
    };
  },

**Comment by tzsk** [comment]
Please state your query properly. What should I make out of this gibberish?

Closing untill further clarification.
