### ISSUE TITLE
Update to Laravel 10

### ISSUE THREAD

**Issue by vonec** [tzsk/payu#363]
Can you update this package to support laravel 10

**Comment by tzsk** [comment]
There's a PR out and it will drop support for PHP 8.0. It will only support PHP 8.1 and above.

**Comment by vonec** [comment]
any eta on when this would be merged

**Comment by vonec** [comment]
may be you should release a new version :)  8.0 support will be till the current version :)

**Comment by tzsk** [comment]
Exactly... That's the plan, it will be a major Version Bump. I'll release it in 1 or 2 days.

**Comment by vonec** [comment]
any updates on this :)

**Comment by tzsk** [comment]
@vonec Released `v7.0.0` with Laravel `10.x` Support. Removed `php-8.0` support.

**Comment by vonec** [comment]
thank you
