### ISSUE TITLE
419 error after redirecting from payment gateway after payment. Laravel version 7.3.0. tzsk/payu version 4.0.0

### ISSUE THREAD

**Issue by abhi-moregau** [tzsk/payu#59]
To reproduce issue at your end create new laravel project with latest version or above 7.0. Then include package tzsk/payu and do the payment as described in document. You will get 419 page after payment process at payment gateway is done and it is redirecting back to your project.

**Comment by tzsk** [comment]
This is a rabbit hole. After fixing this Session Expiry issue. I've got many other issues. Seems like the session is getting wiped out for some reason when it comes back from Payu.

I will have to rewrite a few things to make it work.

**Comment by tzsk** [comment]
It's the new session functionality introduced in Laravel 7.

### Temporary fix.

Set the `same_site` key to `none or null` in `config/sessions.php` file.

### Final-Fix coming soon

**Comment by tzsk** [comment]
Temporarily fixed in `4.0.1`
