### ISSUE TITLE
Argument 1 passed to Tzsk\Payu\Model\PayuPayment::__construct() must be of the type array, null given, called in C:\wamp64\www\sweetnew\vendor\tzsk\payu\src\PayuGateway.php on line 101

### ISSUE THREAD

**Issue by aman90attari** [tzsk/payu#60]
## Detailed description

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used PHP 7.2
Laravel version 6
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:
* ...
* ...

**Comment by tzsk** [comment]
Closing, **No Reproduction Steps Provided**
