### ISSUE TITLE
Enable Laravel8

### ISSUE THREAD

**Issue by uisumo** [tzsk/payu#71]
Hi,

I installed the package after install this package when I try to run: 

php artisan config:cache

It is showing like this:
![image](https://user-images.githubusercontent.com/31437584/93962659-ee0db500-fd78-11ea-9e78-3c6570f194a9.png)

I tried to remove the cache file in bootstrap, still the same error.

**Comment by tzsk** [comment]
@uisumo Thanks for posting a super clean and proper bug report. I'll try and patch it as soon as I can.

**Comment by tzsk** [comment]
@uisumo Just to understand a little more context, which Gateway are you using?

**Comment by tzsk** [comment]
@uisumo Patch released `v5.0.1`. Should be fixed now. Let me know if it's not.
