### ISSUE TITLE
ErrorException Accessing static property Tzsk\Payu\Components\Form::$injectedProps as non static

### ISSUE THREAD

**Issue by frhn404** [tzsk/payu#77]
I am trying to integrate PayU in my laravel 7 application. However on payment inititation I get the following error:
ErrorException
Accessing static property Tzsk\Payu\Components\Form::$injectedProps as non static
I am guessing that it has something to do with the  x-payu-form  component.
Please help me out. Thank You.

**Comment by tzsk** [comment]
@frhn404 Are you trying to modify the Component? Or the loading screen?

Cause as far as I can tell, The component is tested with Snapshots in PhpUnit. And also this static and non static error would have been caught by PSLAM too.

**Comment by frhn404** [comment]
I just tried to initiate a transaction with some basic code. It takes me to the form.blade.php page however the above mentioned error pops up.
I didn't modify the loading screen. Removing the  x-payu-form element from the form page renders the page normally and the error orginates from it.

**Comment by tzsk** [comment]
@frhn404 can you show your code? Did you publish the Form blade view?

**Comment by frhn404** [comment]
I tried it both with and without publishing the form blade view. 
Following are the controller and the error images:
![controller](https://user-images.githubusercontent.com/63193849/94522291-0be18b00-024d-11eb-94f2-f40732e0ba35.JPG)
![error](https://user-images.githubusercontent.com/63193849/94522300-0e43e500-024d-11eb-98d6-340a6925b506.JPG)

Thanks alot for your time

**Comment by tzsk** [comment]
@frhn404 Can you try and delete the vendor folder and reinstall everything? See if that helps.

**Comment by frhn404** [comment]
Thanks a lot. Works flawlessly now after removing and reinstalling.
Appreciate your prompt help and thanks for this awesome package.
